vagasData = [
    {
        "id": "1",
        "title": "Estágio em Desenvolvimento Front-End",
        "createdAt": "2025-04-29T09:00:00Z",
        "subscriptions": 0,
        "publicationPlataform": "LinkedIn",
        "description": "Conhecimentos em HTML, CSS, JavaScript e React.",
        "modalidade": "remoto",
        "nível": "estágio",
        "subscriptionRef": "https://www.linkedin.com/jobs/view/1",
        "requisitos": ["HTML", "CSS", "JavaScript", "React"],
        "turno": "matutino",
        "empresa": "TechWave",
        "bolsa": 1200.0
    },
    {
        "id": "2",
        "title": "Estágio em Ciência de Dados",
        "createdAt": "2025-04-28T15:00:00Z",
        "publicationPlataform": "Gupy",
        "subscriptions": 0,
        "description": "Análise de dados, Python, SQL, Power BI.",
        "modalidade": "híbrido",
        "nível": "estágio",
        "subscriptionRef": "https://www.gupy.io/jobs/view/2",
        "requisitos": ["Python", "SQL", "Power BI"],
        "turno": "vespertino",
        "empresa": "DataX",
        "bolsa": 1400.0
    },
    {
        "id": "3",
        "title": "Estágio em UX/UI Design",
        "subscriptions": 0,
        "createdAt": "2025-04-26T10:00:00Z",
        "publicationPlataform": "Kenoby",
        "description": "Prototipação em Figma, testes de usabilidade.",
        "modalidade": "presencial",
        "nível": "estágio",
        "subscriptions": 0,
        "subscriptionRef": "https://www.kenoby.com/jobs/view/3",
        "requisitos": ["Figma", "Design Thinking"],
        "turno": "integral",
        "empresa": "DesignPro",
        "bolsa": 1100.0
    },
    {
        "id": "4",
        "title": "Trainee em Engenharia de Software",
        "createdAt": "2025-04-25T14:00:00Z",
        "subscriptions": 0,
        "publicationPlataform": "LinkedIn",
        "description": "Ciclo completo de desenvolvimento, testes, APIs.",
        "modalidade": "híbrido",
        "nível": "trainee",
        "subscriptionRef": "https://www.linkedin.com/jobs/view/4",
        "requisitos": ["Java", "Spring", "REST API"],
        "turno": "integral",
        "empresa": "SoftEng Corp",
        "bolsa": 2500.0
    },
    {
        "id": "5",
        "title": "Estágio Back-End Java",
        "subscriptions": 0,
        "createdAt": "2025-04-24T11:00:00Z",
        "publicationPlataform": "Gupy",
        "description": "Desenvolvimento de APIs REST com Spring Boot.",
        "modalidade": "remoto",
        "nível": "estágio",
        "subscriptionRef": "https://www.gupy.io/jobs/view/5",
        "requisitos": ["Java", "Spring Boot", "Git"],
        "turno": "matutino",
        "empresa": "CodeBase",
        "bolsa": 1300.0
    },
    {
        "id": "6",
        "title": "Estágio DevOps",
        "createdAt": "2025-04-23T17:00:00Z",
        "publicationPlataform": "99jobs",
        "description": "CI/CD, Docker, Linux, monitoramento com Prometheus.",
        "modalidade": "híbrido",
        "nível": "estágio",
        "subscriptions": 0,
        "subscriptionRef": "https://www.99jobs.com/job/6",
        "requisitos": ["Docker", "Linux", "Prometheus"],
        "turno": "noturno",
        "empresa": "InfraX",
        "bolsa": 1500.0
    },
    {
        "id": "7",
        "title": "Estágio QA / Testes de Software",
        "subscriptions": 0,
        "createdAt": "2025-04-22T13:00:00Z",
        "publicationPlataform": "LinkedIn",
        "description": "Testes automatizados com Selenium e Jest.",
        "modalidade": "remoto",
        "nível": "estágio",
        "subscriptionRef": "https://www.linkedin.com/jobs/view/7",
        "requisitos": ["Selenium", "Jest"],
        "turno": "vespertino",
        "empresa": "Testify",
        "bolsa": 1250.0
    },
    {
        "id": "8",
        "title": "Estágio em Segurança da Informação",
        "subscriptions": 0,
        "createdAt": "2025-04-21T16:00:00Z",
        "publicationPlataform": "Gupy",
        "description": "Análise de vulnerabilidades, redes, criptografia.",
        "modalidade": "presencial",
        "nível": "estágio",
        "subscriptionRef": "https://www.gupy.io/jobs/view/8",
        "requisitos": ["Redes", "Segurança", "Criptografia"],
        "turno": "integral",
        "empresa": "SecureIT",
        "bolsa": 1350.0
    },
    {
        "id": "9",
        "title": "Estágio em Banco de Dados",
        "subscriptions": 0,
        "createdAt": "2025-04-20T09:00:00Z",
        "publicationPlataform": "Kenoby",
        "description": "Modelagem, consultas em MySQL e MongoDB.",
        "modalidade": "remoto",
        "nível": "estágio",
        "subscriptionRef": "https://www.kenoby.com/jobs/view/9",
        "requisitos": ["MySQL", "MongoDB", "Modelagem de Dados"],
        "turno": "matutino",
        "empresa": "DataBank",
        "bolsa": 1200.0
    },
    {
        "id": "10",
        "title": "Estágio Full Stack",
        "createdAt": "2025-04-19T12:00:00Z",
        "publicationPlataform": "LinkedIn",
        "description": "React no front-end e Node.js no back-end.",
        "modalidade": "remoto",
        "nível": "estágio",
        "subscriptionRef": "https://www.linkedin.com/jobs/view/10",
        "subscriptions": 0,
        "requisitos": ["React", "Node.js", "APIs REST"],
        "turno": "vespertino",
        "empresa": "FullDev",
        "bolsa": 1450.0
    }
]
